/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Izumi Radzuan
 */
public class vmMainCP extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public vmMainCP(engine runtime) {
        initComponents();
        PasswordInvalid.setForeground(Color.GREEN);
        this.runtime=runtime;
        PasswordBox.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e){
                displayChange();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                displayChange();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e){
                displayChange();
            }
            
            public void displayChange(){
                String input = (String) PasswordBox.getText();
                if(input.equals(runtime.getPassword())){
                    unlock=1;
                    PasswordValid.setForeground(Color.GREEN);
                    PasswordInvalid.setForeground(Color.BLACK);
                }else{
                    PasswordInvalid.setForeground(Color.GREEN);
                    PasswordValid.setForeground(Color.BLACK);
                    unlock=0;
                    totalVdenom.setText("");
                    DPriceChange.setText("");
                    TotalCash.setText("");
                    AllCView.setText("");
                }
                //System.out.println(PasswordBox.getText());
            }

        });
        DPriceChange.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e){
                displayChange();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                displayChange();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e){
                displayChange();
            }
            
            public void displayChange(){
                int newPrice;
                if("".equals((String) DPriceChange.getText())) 
                    newPrice=0;
                else
                    newPrice= Integer.parseInt((String) DPriceChange.getText());
                
                if(unlock==1&&brand!=100){
                    runtime.setPrice(brand,newPrice);
                }
                //System.out.println(PasswordBox.getText());
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        VimtoSDDispenser = new javax.swing.JLabel();
        MCPanel = new javax.swing.JLabel();
        PswrdPanel = new javax.swing.JPanel();
        PswrdTiltle = new javax.swing.JLabel();
        PasswordBox = new javax.swing.JPasswordField();
        PasswordValid = new javax.swing.JLabel();
        PasswordInvalid = new javax.swing.JLabel();
        CoinDenomPanel = new javax.swing.JPanel();
        DenominationTile = new javax.swing.JLabel();
        coin10 = new javax.swing.JButton();
        coin20 = new javax.swing.JButton();
        coin50 = new javax.swing.JButton();
        coin100 = new javax.swing.JButton();
        totaldenom = new javax.swing.JLabel();
        totalVdenom = new javax.swing.JTextField();
        NewPricePanel = new javax.swing.JPanel();
        DPriceTile = new javax.swing.JLabel();
        DPriceChange = new javax.swing.JTextField();
        TotalCashPanel = new javax.swing.JPanel();
        SeeTotal = new javax.swing.JButton();
        TotalCash = new javax.swing.JTextField();
        PressCPanel = new javax.swing.JPanel();
        CollectTile = new javax.swing.JLabel();
        CCashButton = new javax.swing.JRadioButton();
        CollectCPanel = new javax.swing.JPanel();
        TakeCTile = new javax.swing.JLabel();
        AllCView = new javax.swing.JTextField();
        ShutDownPanel = new javax.swing.JPanel();
        ShutDTile = new javax.swing.JLabel();
        ShutDButton = new javax.swing.JButton();
        BrandButtonPanel = new javax.swing.JPanel();
        B1Button = new javax.swing.JButton();
        B2Button = new javax.swing.JButton();
        B3Button = new javax.swing.JButton();
        B4Button = new javax.swing.JButton();
        B5Button = new javax.swing.JButton();
        B6Button = new javax.swing.JButton();
        B7Button = new javax.swing.JButton();
        B8Button = new javax.swing.JButton();
        B9Button = new javax.swing.JButton();
        B10Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VimtoSDDispenser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VimtoSDDispenser.setText("VIMTO SOFT DRINKS DISPENSER");

        MCPanel.setText("MAINTAINER CONTROL PANEL");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VimtoSDDispenser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(MCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(158, 158, 158))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addComponent(VimtoSDDispenser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PswrdTiltle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PswrdTiltle.setText("TYPE PASSWORD HERE");

        PasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBoxActionPerformed(evt);
            }
        });

        PasswordValid.setText("PASSWORD VALID");

        PasswordInvalid.setText("PASSWORD INVALID");

        javax.swing.GroupLayout PswrdPanelLayout = new javax.swing.GroupLayout(PswrdPanel);
        PswrdPanel.setLayout(PswrdPanelLayout);
        PswrdPanelLayout.setHorizontalGroup(
            PswrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PswrdPanelLayout.createSequentialGroup()
                .addGroup(PswrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PswrdPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(PasswordValid, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PswrdPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(PswrdTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PswrdPanelLayout.setVerticalGroup(
            PswrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PswrdPanelLayout.createSequentialGroup()
                .addGroup(PswrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PswrdTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PswrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordInvalid, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(PasswordValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        DenominationTile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DenominationTile.setText("PRESS BELOW TO DETERMINE NUMBER OF COINS IN SELECTED DENOMINATION");

        coin10.setText("10c");
        coin10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin10ActionPerformed(evt);
            }
        });

        coin20.setText("20c");
        coin20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin20ActionPerformed(evt);
            }
        });

        coin50.setText("50c");
        coin50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin50ActionPerformed(evt);
            }
        });

        coin100.setText("100c");
        coin100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin100ActionPerformed(evt);
            }
        });

        totaldenom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totaldenom.setText("TOTAL NUMBER OF COINS IN SELECTED DENOMINATION");

        totalVdenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalVdenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVdenomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoinDenomPanelLayout = new javax.swing.GroupLayout(CoinDenomPanel);
        CoinDenomPanel.setLayout(CoinDenomPanelLayout);
        CoinDenomPanelLayout.setHorizontalGroup(
            CoinDenomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoinDenomPanelLayout.createSequentialGroup()
                .addGroup(CoinDenomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoinDenomPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(coin10)
                        .addGap(48, 48, 48)
                        .addComponent(coin20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(coin50)
                        .addGap(43, 43, 43)
                        .addComponent(coin100)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CoinDenomPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totaldenom, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalVdenom, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(CoinDenomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DenominationTile, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CoinDenomPanelLayout.setVerticalGroup(
            CoinDenomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoinDenomPanelLayout.createSequentialGroup()
                .addComponent(DenominationTile, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(CoinDenomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coin10)
                    .addComponent(coin20)
                    .addComponent(coin50)
                    .addComponent(coin100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CoinDenomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalVdenom, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
        );

        DPriceTile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DPriceTile.setText("TYPE NEW DRINKS CAN PRICE HERE");

        DPriceChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout NewPricePanelLayout = new javax.swing.GroupLayout(NewPricePanel);
        NewPricePanel.setLayout(NewPricePanelLayout);
        NewPricePanelLayout.setHorizontalGroup(
            NewPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPricePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DPriceTile, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        NewPricePanelLayout.setVerticalGroup(
            NewPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPricePanelLayout.createSequentialGroup()
                .addGroup(NewPricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DPriceTile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SeeTotal.setText("PRESS HERE FOR TOTAL CASH HELD BY MACHINE");
        SeeTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TotalCashPanelLayout = new javax.swing.GroupLayout(TotalCashPanel);
        TotalCashPanel.setLayout(TotalCashPanelLayout);
        TotalCashPanelLayout.setHorizontalGroup(
            TotalCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalCashPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SeeTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalCash, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        TotalCashPanelLayout.setVerticalGroup(
            TotalCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SeeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TotalCash, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CollectTile.setText("PRESS HERE TO COLLECT ALL CASH");

        CCashButton.setText("PRESS");
        CCashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCashButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PressCPanelLayout = new javax.swing.GroupLayout(PressCPanel);
        PressCPanel.setLayout(PressCPanelLayout);
        PressCPanelLayout.setHorizontalGroup(
            PressCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PressCPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(CollectTile, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(CCashButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PressCPanelLayout.setVerticalGroup(
            PressCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PressCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CollectTile, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addComponent(CCashButton))
        );

        TakeCTile.setText("COLLECT ALL CASH HERE");

        javax.swing.GroupLayout CollectCPanelLayout = new javax.swing.GroupLayout(CollectCPanel);
        CollectCPanel.setLayout(CollectCPanelLayout);
        CollectCPanelLayout.setHorizontalGroup(
            CollectCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollectCPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TakeCTile, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AllCView, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        CollectCPanelLayout.setVerticalGroup(
            CollectCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CollectCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(AllCView, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addComponent(TakeCTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ShutDTile.setText("PRESS HERE WHEN FINISHED");

        ShutDButton.setText("FINISHED");
        ShutDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShutDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShutDownPanelLayout = new javax.swing.GroupLayout(ShutDownPanel);
        ShutDownPanel.setLayout(ShutDownPanelLayout);
        ShutDownPanelLayout.setHorizontalGroup(
            ShutDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShutDownPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ShutDTile, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShutDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        ShutDownPanelLayout.setVerticalGroup(
            ShutDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShutDownPanelLayout.createSequentialGroup()
                .addGroup(ShutDownPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShutDTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ShutDownPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ShutDButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        B1Button.setText("BRAND 1");
        B1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ButtonActionPerformed(evt);
            }
        });

        B2Button.setText("BRAND 2");
        B2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ButtonActionPerformed(evt);
            }
        });

        B3Button.setText("BRAND 3");
        B3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ButtonActionPerformed(evt);
            }
        });

        B4Button.setText("BRAND 4");
        B4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ButtonActionPerformed(evt);
            }
        });

        B5Button.setText("BRAND 5");
        B5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ButtonActionPerformed(evt);
            }
        });

        B6Button.setText("BRAND 6");
        B6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ButtonActionPerformed(evt);
            }
        });

        B7Button.setText("BRAND 7");
        B7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ButtonActionPerformed(evt);
            }
        });

        B8Button.setText("BRAND 8");
        B8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ButtonActionPerformed(evt);
            }
        });

        B9Button.setText("BRAND 9");
        B9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ButtonActionPerformed(evt);
            }
        });

        B10Button.setText("BRAND 10");
        B10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BrandButtonPanelLayout = new javax.swing.GroupLayout(BrandButtonPanel);
        BrandButtonPanel.setLayout(BrandButtonPanelLayout);
        BrandButtonPanelLayout.setHorizontalGroup(
            BrandButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrandButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BrandButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BrandButtonPanelLayout.createSequentialGroup()
                        .addComponent(B1Button)
                        .addGap(18, 18, 18)
                        .addComponent(B2Button)
                        .addGap(18, 18, 18)
                        .addComponent(B3Button)
                        .addGap(18, 18, 18)
                        .addComponent(B4Button)
                        .addGap(18, 18, 18)
                        .addComponent(B5Button))
                    .addGroup(BrandButtonPanelLayout.createSequentialGroup()
                        .addComponent(B6Button)
                        .addGap(18, 18, 18)
                        .addComponent(B7Button)
                        .addGap(18, 18, 18)
                        .addComponent(B8Button)
                        .addGap(18, 18, 18)
                        .addComponent(B9Button)
                        .addGap(14, 14, 14)
                        .addComponent(B10Button)))
                .addGap(34, 34, 34))
        );
        BrandButtonPanelLayout.setVerticalGroup(
            BrandButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrandButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BrandButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1Button)
                    .addComponent(B2Button)
                    .addComponent(B3Button)
                    .addComponent(B4Button)
                    .addComponent(B5Button))
                .addGap(18, 18, 18)
                .addGroup(BrandButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B6Button)
                    .addComponent(B7Button)
                    .addComponent(B8Button)
                    .addComponent(B9Button)
                    .addComponent(B10Button))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PswrdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CoinDenomPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NewPricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TotalCashPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PressCPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CollectCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShutDownPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BrandButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PswrdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoinDenomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BrandButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PressCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CollectCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShutDownPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void coin10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin10ActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            totalVdenom.setText(Integer.toString(runtime.get10c()));
        }
        
    }//GEN-LAST:event_coin10ActionPerformed

    private void totalVdenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVdenomActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            
        }
    }//GEN-LAST:event_totalVdenomActionPerformed

    private void ShutDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShutDButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            
        }
    }//GEN-LAST:event_ShutDButtonActionPerformed

    private void coin20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin20ActionPerformed
        
        if(unlock==1){
            totalVdenom.setText(Integer.toString(runtime.get20c()));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_coin20ActionPerformed

    private void coin50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin50ActionPerformed
        if(unlock==1){
            totalVdenom.setText(Integer.toString(runtime.get50c()));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_coin50ActionPerformed

    private void coin100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin100ActionPerformed
        if(unlock==1){
            totalVdenom.setText(Integer.toString(runtime.get100c()));
        }
    }//GEN-LAST:event_coin100ActionPerformed

    private void SeeTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeTotalActionPerformed
        if(unlock==1){
            TotalCash.setText(Integer.toString(runtime.getTotalCash()));
        }
        
    }//GEN-LAST:event_SeeTotalActionPerformed

    private void CCashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCashButtonActionPerformed
        if(unlock==1){
            AllCView.setText(Integer.toString(runtime.getTotalCash()));
            TotalCash.setText("");
        }
        
    }//GEN-LAST:event_CCashButtonActionPerformed

    private void B4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ButtonActionPerformed
       if(unlock==1){
            brand=3;
        }
    }//GEN-LAST:event_B4ButtonActionPerformed

    private void B5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=4;
        }
    }//GEN-LAST:event_B5ButtonActionPerformed

    private void PasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordBoxActionPerformed
        
    }//GEN-LAST:event_PasswordBoxActionPerformed

    private void B1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=0;
        }
    }//GEN-LAST:event_B1ButtonActionPerformed

    private void B2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=1;
        }
    }//GEN-LAST:event_B2ButtonActionPerformed

    private void B3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=2;
        }
    }//GEN-LAST:event_B3ButtonActionPerformed

    private void B6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=5;
        }
    }//GEN-LAST:event_B6ButtonActionPerformed

    private void B7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=6;
        }
    }//GEN-LAST:event_B7ButtonActionPerformed

    private void B8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
           brand=7; 
        }
    }//GEN-LAST:event_B8ButtonActionPerformed

    private void B9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=8;
        }
    }//GEN-LAST:event_B9ButtonActionPerformed

    private void B10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ButtonActionPerformed
        // TODO add your handling code here:
        if(unlock==1){
            brand=9;
        }
    }//GEN-LAST:event_B10ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vmMainCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vmMainCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vmMainCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vmMainCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllCView;
    private javax.swing.JButton B10Button;
    private javax.swing.JButton B1Button;
    private javax.swing.JButton B2Button;
    private javax.swing.JButton B3Button;
    private javax.swing.JButton B4Button;
    private javax.swing.JButton B5Button;
    private javax.swing.JButton B6Button;
    private javax.swing.JButton B7Button;
    private javax.swing.JButton B8Button;
    private javax.swing.JButton B9Button;
    private javax.swing.JPanel BrandButtonPanel;
    private javax.swing.JRadioButton CCashButton;
    private javax.swing.JPanel CoinDenomPanel;
    private javax.swing.JPanel CollectCPanel;
    private javax.swing.JLabel CollectTile;
    private javax.swing.JTextField DPriceChange;
    private javax.swing.JLabel DPriceTile;
    private javax.swing.JLabel DenominationTile;
    private javax.swing.JLabel MCPanel;
    private javax.swing.JPanel NewPricePanel;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JLabel PasswordInvalid;
    private javax.swing.JLabel PasswordValid;
    private javax.swing.JPanel PressCPanel;
    private javax.swing.JPanel PswrdPanel;
    private javax.swing.JLabel PswrdTiltle;
    private javax.swing.JButton SeeTotal;
    private javax.swing.JButton ShutDButton;
    private javax.swing.JLabel ShutDTile;
    private javax.swing.JPanel ShutDownPanel;
    private javax.swing.JLabel TakeCTile;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JTextField TotalCash;
    private javax.swing.JPanel TotalCashPanel;
    private javax.swing.JLabel VimtoSDDispenser;
    private javax.swing.JButton coin10;
    private javax.swing.JButton coin100;
    private javax.swing.JButton coin20;
    private javax.swing.JButton coin50;
    private javax.swing.JTextField totalVdenom;
    private javax.swing.JLabel totaldenom;
    // End of variables declaration//GEN-END:variables
    engine runtime;
   // String password="123abc";
    int unlock,brand=100;
   // String input;
}
